# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-22 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180522_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='flyers'),
        ),
        migrations.AlterField(
            model_name='event',
            name='more_details_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
